#!/bin/bash

if [[ ! $(whoami) == "root" ]]; then
    echo "ERROR: You need to be root in order to run SANEi."
    exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}")" )" && pwd )"

if [[ "${BASH_SOURCE[0]}" =~ sanmod$ ]]; then
	${SCRIPT_DIR}/sanei module "${@}"
	exit 0
fi

if ! source "${SCRIPT_DIR}/sanei-core/lib/sanei.sh"; then
    echo "ERROR: Missing library file."
    exit 1
fi

# TODO: set -e
# set SANEI_AUTOMATIC_SELFPUSH or SANEI_AUTOMATIC_SELFUPGRADE to automatically upgrade SANEI before every run
sanei_automatic_selfupgrade

INVOKED_COUNT=0 sanei_invoke_module_script sanei ${ARGUMENTS[@]}
